rvm:
  - 2.2.3
addons:
  postgresql: "9.4"

before_install:
  - "gem install bundler"

before_script:
  - "cp config/database.sample.yml config/database.yml"
  - "psql -c 'create role hack4ec SUPERUSER LOGIN;' postgres"
  - "psql -c 'create database hack4ec_test;' -U hack4ec postgres"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake db:migrate"

env:
  - DISPLAY=:99.0

script:
  - "bundle exec rspec spec"
    #- "bundle exec rake jasmine:ci" removed while jasmine has some bugs with ruby 2.1.0

branches:
  only:
    - master
    - bootstrap
